version: '3'
services:
  mysql:
    image: mysql:8.0.32-oracle
    ports:
     - 3306:3306
    environment:
     - MYSQL_USER=sheen
     - MYSQL_PASSWORD=@dm1n@local.net
     - MYSQL_ROOT_PASSWORD=@dm1n@local.net
     - MYSQL_DATABASE=my_db
    container_name: mysql
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: always
    ports:
     - 8081:80
    environment:
     - MYSQL_USER=sheen
     - MYSQL_PASSWORD=@dm1n@local.net
     - MYSQL_ROOT_PASSWORD=@dm1n@local.net
     - PMA_HOST=mysql
    container_name: phpmyadmin
    depends_on:
     - "mysql"
